version: "1.0"

services:
  node_app:
    container_name: api_nw
    build: .
    image: nithoam/api_nw
    ports:
      - "3000:3000"
    environment:
      - PG_DB=api_nw_db
      - PG_USER=nicolas
      - PG_PASSWORD=password
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=api_nw_db
      - POSTGRES_USER=nicolas
      - POSTGRES_PASSWORD=password
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}



